import {
  AlertCircleIcon,
  ArchiveIcon,
  BellIcon,
  BoxIcon,
  CalendarClockIcon,
  CheckCircle2Icon,
  CircleIcon,
  ClipboardCheckIcon,
  ClockIcon,
  FlagIcon,
  HourglassIcon,
  InboxIcon,
  LayersIcon,
  type LucideIcon,
  PackageIcon,
  PaletteIcon,
  PencilRulerIcon,
  PenToolIcon,
  PrinterIcon,
  RotateCcwIcon,
  ScissorsIcon,
  SendIcon,
  ShieldCheckIcon,
  StampIcon,
  StarIcon,
  TagIcon,
  ThumbsUpIcon,
  TruckIcon,
  Undo2Icon,
  WrenchIcon,
  XCircleIcon,
} from "lucide-react"

/** A fixed, curated set of icon keys admins can assign to an order status. Each key is an
 * opaque string as far as the backend is concerned (same convention as AVATAR_KEYS/
 * avatars.ts) — only this map interprets it. Covers every icon the 11 built-in statuses
 * already use, plus spares for custom statuses. */
export const ORDER_STATUS_ICON_KEYS = [
  "clock",
  "pencil-ruler",
  "pen-tool",
  "printer",
  "scissors",
  "package",
  "truck",
  "check-circle-2",
  "x-circle",
  "rotate-ccw",
  "undo-2",
  "circle",
  "box",
  "layers",
  "stamp",
  "tag",
  "flag",
  "bell",
  "archive",
  "send",
  "inbox",
  "hourglass",
  "calendar-clock",
  "wrench",
  "palette",
  "star",
  "thumbs-up",
  "alert-circle",
  "shield-check",
  "clipboard-check",
] as const

export type OrderStatusIconKey = (typeof ORDER_STATUS_ICON_KEYS)[number]

const ORDER_STATUS_ICON_MAP: Record<OrderStatusIconKey, LucideIcon> = {
  clock: ClockIcon,
  "pencil-ruler": PencilRulerIcon,
  "pen-tool": PenToolIcon,
  printer: PrinterIcon,
  scissors: ScissorsIcon,
  package: PackageIcon,
  truck: TruckIcon,
  "check-circle-2": CheckCircle2Icon,
  "x-circle": XCircleIcon,
  "rotate-ccw": RotateCcwIcon,
  "undo-2": Undo2Icon,
  circle: CircleIcon,
  box: BoxIcon,
  layers: LayersIcon,
  stamp: StampIcon,
  tag: TagIcon,
  flag: FlagIcon,
  bell: BellIcon,
  archive: ArchiveIcon,
  send: SendIcon,
  inbox: InboxIcon,
  hourglass: HourglassIcon,
  "calendar-clock": CalendarClockIcon,
  wrench: WrenchIcon,
  palette: PaletteIcon,
  star: StarIcon,
  "thumbs-up": ThumbsUpIcon,
  "alert-circle": AlertCircleIcon,
  "shield-check": ShieldCheckIcon,
  "clipboard-check": ClipboardCheckIcon,
}

/** Looks up an icon key's component, falling back to a generic circle for an
 * unrecognized/legacy key (the backend stores `icon` as opaque, unvalidated text). */
export function getOrderStatusIcon(key: string): LucideIcon {
  return ORDER_STATUS_ICON_MAP[key as OrderStatusIconKey] ?? CircleIcon
}
