import { CalendarIcon, LockIcon, ReceiptTextIcon } from "lucide-react"
import { useEffect, useState } from "react"
import { format, parseISO, subDays } from "date-fns"
import { toast } from "sonner"

import { ChoiceTile } from "@/components/choice-tile"
import {
  EXPENSE_NOTES_MAX_LENGTH,
  ExpenseAmountField,
  ExpenseCategoryField,
  ExpenseNotesField,
  PaymentMethodTiles,
} from "@/components/expenses/expense-fields"
import { FormDialogHeader } from "@/components/form-dialog-header"
import { Button } from "@/components/ui/button"
import { Calendar } from "@/components/ui/calendar"
import { Dialog, DialogBody, DialogContent, DialogFooter } from "@/components/ui/dialog"
import { Field, FieldError, FieldGroup, FieldLabel } from "@/components/ui/field"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import { Spinner } from "@/components/ui/spinner"
import { ToggleGroup } from "@/components/ui/toggle-group"
import {
  useExpenseActions,
  type Expense,
  type ExpenseAutoSource,
  type ExpenseInput,
} from "@/lib/expenses"
import { useEnabledPaymentMethods } from "@/lib/payment-methods"
import { formatCurrency, formatDate } from "@/lib/utils"
import { maxLengthMessage, parsePositiveAmount, positiveAmountMessage, requiredMessage } from "@/lib/validation"

const AUTO_SOURCE_TITLES: Record<ExpenseAutoSource, string> = {
  commission_release: "Created by a commission release",
  monthly_incentive_release: "Created by a monthly incentive release",
}

const ISO = "yyyy-MM-dd"

function emptyDraft(): ExpenseInput {
  return {
    date: format(new Date(), ISO),
    amount: 0,
    category: "",
    paymentMethod: "",
    notes: "",
  }
}

function draftFromExpense(expense: Expense): ExpenseInput {
  return {
    date: expense.date,
    amount: expense.amount,
    category: expense.category,
    paymentMethod: expense.paymentMethod,
    notes: expense.notes,
  }
}

export function ExpenseFormDialog({
  open,
  onOpenChange,
  expense,
  onSaved,
}: {
  open: boolean
  onOpenChange: (open: boolean) => void
  expense: Expense | null
  onSaved?: () => void
}) {
  const { addExpense, updateExpense } = useExpenseActions()
  const { paymentMethods: enabledMethods } = useEnabledPaymentMethods()
  const autoSource = expense?.autoGeneratedSource ?? null
  const isLocked = !!autoSource
  const [draft, setDraft] = useState<ExpenseInput>(emptyDraft)
  const [amountInput, setAmountInput] = useState("")
  const [dateError, setDateError] = useState<string | null>(null)
  const [amountError, setAmountError] = useState<string | null>(null)
  const [categoryError, setCategoryError] = useState<string | null>(null)
  const [paymentMethodError, setPaymentMethodError] = useState<string | null>(null)
  const [notesError, setNotesError] = useState<string | null>(null)
  const [datePickerOpen, setDatePickerOpen] = useState(false)
  const [isSubmitting, setIsSubmitting] = useState(false)

  useEffect(() => {
    if (!open) return
    const next = expense ? draftFromExpense(expense) : emptyDraft()
    setDraft(next)
    setAmountInput(expense ? String(expense.amount) : "")
    setDateError(null)
    setAmountError(null)
    setCategoryError(null)
    setPaymentMethodError(null)
    setNotesError(null)
  }, [open, expense])

  // Quick dates: most expenses are logged the day they happen, or the day after.
  const today = format(new Date(), ISO)
  const yesterday = format(subDays(new Date(), 1), ISO)
  const quickDate = draft.date === today ? "today" : draft.date === yesterday ? "yesterday" : null

  function setDate(iso: string) {
    setDraft((prev) => ({ ...prev, date: iso }))
    setDateError(null)
  }

  // "₱1,200.00 · Office Supplies and Equipment · Cash" — builds up as the form is filled in.
  const previewAmount = parsePositiveAmount(amountInput)
  const recap = [
    previewAmount !== null ? formatCurrency(previewAmount) : null,
    draft.category || null,
    draft.paymentMethod || null,
  ].filter(Boolean)

  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault()

    if (!draft.date) {
      setDateError(requiredMessage("Date"))
      return
    }
    const amount = parsePositiveAmount(amountInput)
    if (amount === null) {
      setAmountError(positiveAmountMessage("amount"))
      return
    }
    if (!draft.category) {
      setCategoryError(requiredMessage("Category"))
      return
    }
    if (!draft.paymentMethod) {
      setPaymentMethodError(requiredMessage("Payment method"))
      return
    }
    if (draft.notes.length > EXPENSE_NOTES_MAX_LENGTH) {
      setNotesError(maxLengthMessage("Notes", EXPENSE_NOTES_MAX_LENGTH))
      return
    }

    const payload: ExpenseInput = { ...draft, amount }

    setIsSubmitting(true)
    try {
      if (expense) {
        await updateExpense(expense.id, payload)
        toast.success("Expense updated.")
      } else {
        await addExpense(payload)
        toast.success("Expense created.")
      }
      onOpenChange(false)
      onSaved?.()
    } catch (err) {
      toast.error(typeof err === "string" ? err : "Failed to save expense.")
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <FormDialogHeader
          icon={ReceiptTextIcon}
          title={expense ? "Edit expense" : "New expense"}
          description={
            expense
              ? expense.createdByName
                ? `Logged by ${expense.createdByName} · ${formatDate(expense.createdAt)}`
                : `Logged ${formatDate(expense.createdAt)}`
              : "Log a new business expense."
          }
        />

        <DialogBody>
          <form id="expense-form" onSubmit={handleSubmit} className="flex flex-col gap-4">
            {autoSource && (
              <div className="flex gap-2.5 rounded-lg border bg-muted/40 px-3 py-2.5 text-sm">
                <LockIcon aria-hidden className="mt-0.5 size-4 shrink-0 text-muted-foreground" />
                <div className="flex flex-col gap-0.5">
                  <span className="font-medium">{AUTO_SOURCE_TITLES[autoSource]}</span>
                  <span className="text-muted-foreground">
                    Amount, category and date are locked. Undo the release on the Incentives page to change them.
                  </span>
                </div>
              </div>
            )}
            <FieldGroup>
              <ExpenseAmountField
                id="expense-amount"
                value={amountInput}
                error={amountError}
                disabled={isLocked}
                autoFocus={!expense}
                onChange={(value) => {
                  setAmountInput(value)
                  setAmountError(null)
                }}
              />

              <Field data-invalid={!!dateError}>
                <FieldLabel id="expense-date-label">Date</FieldLabel>
                <div className="flex flex-wrap items-center gap-2">
                  <ToggleGroup
                    aria-labelledby="expense-date-label"
                    value={quickDate ? [quickDate] : []}
                    disabled={isLocked}
                    onValueChange={(next) => {
                      if (next[0] === "today") setDate(today)
                      else if (next[0] === "yesterday") setDate(yesterday)
                    }}
                    className="gap-2"
                  >
                    <ChoiceTile value="today">Today</ChoiceTile>
                    <ChoiceTile value="yesterday">Yesterday</ChoiceTile>
                  </ToggleGroup>
                  <Popover open={datePickerOpen} onOpenChange={setDatePickerOpen}>
                    <PopoverTrigger
                      id="expense-date"
                      disabled={isLocked}
                      render={
                        <Button
                          type="button"
                          variant="outline"
                          size="sm"
                          className={
                            quickDate
                              ? "font-normal text-muted-foreground"
                              : "border-primary bg-accent font-normal text-accent-foreground hover:bg-accent"
                          }
                          aria-invalid={!!dateError}
                        />
                      }
                    >
                      <CalendarIcon data-icon="inline-start" />
                      {quickDate || !draft.date ? "Other date…" : format(parseISO(draft.date), "MMM d, yyyy")}
                    </PopoverTrigger>
                    <PopoverContent className="w-auto p-0" align="start">
                      <Calendar
                        mode="single"
                        selected={draft.date ? parseISO(draft.date) : undefined}
                        onSelect={(date) => {
                          setDate(date ? format(date, ISO) : "")
                          setDatePickerOpen(false)
                        }}
                        autoFocus
                      />
                    </PopoverContent>
                  </Popover>
                </div>
                <FieldError>{dateError ?? undefined}</FieldError>
              </Field>

              <ExpenseCategoryField
                id="expense-category"
                value={draft.category}
                error={categoryError}
                disabled={isLocked}
                onChange={(value) => {
                  setDraft((prev) => ({ ...prev, category: value }))
                  setCategoryError(null)
                }}
              />

              <PaymentMethodTiles
                id="expense-payment-method"
                value={draft.paymentMethod}
                methods={enabledMethods}
                error={paymentMethodError}
                onChange={(value) => {
                  setDraft((prev) => ({ ...prev, paymentMethod: value }))
                  setPaymentMethodError(null)
                }}
              />

              <ExpenseNotesField
                id="expense-notes"
                value={draft.notes}
                error={notesError}
                onChange={(value) => {
                  setDraft((prev) => ({ ...prev, notes: value }))
                  setNotesError(null)
                }}
              />
            </FieldGroup>
          </form>
        </DialogBody>

        <DialogFooter className="sm:items-center">
          <p className="mr-auto hidden min-w-0 truncate text-sm text-muted-foreground tabular-nums sm:block">
            {recap.join(" · ")}
          </p>
          <Button variant="ghost" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button type="submit" form="expense-form" disabled={isSubmitting}>
            {isSubmitting && <Spinner data-icon="inline-start" />}
            {isSubmitting ? "Saving…" : expense ? "Save changes" : "Add expense"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
