import { type MouseEvent, type ReactNode } from "react"
import {
  Loader2Icon,
  MoreHorizontalIcon,
  PencilIcon,
  PlusIcon,
  ReceiptTextIcon,
  Trash2Icon,
  TriangleAlertIcon,
  XIcon,
} from "lucide-react"

import { DataCardItem, DataCardList, DataCardListSkeleton } from "@/components/data-card-list"
import { Badge } from "@/components/ui/badge"
import { TABLE_HEAD_CLASS, TABLE_HEADER_CLASS, TABLE_SURFACE_CLASS } from "@/components/table-surface"
import { Button } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import {
  Empty,
  EmptyContent,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from "@/components/ui/empty"
import { Skeleton } from "@/components/ui/skeleton"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip"
import type { Expense, ExpenseAutoSource } from "@/lib/expenses"
import { cn, formatCurrency, formatDate } from "@/lib/utils"

const AUTO_SOURCE_LABELS: Record<ExpenseAutoSource, string> = {
  commission_release: "Created by a commission release",
  monthly_incentive_release: "Created by a monthly incentive release",
}

const AUTO_DELETE_REASON = "Undo the release on the Incentives page to remove it."

function Columns({ canManage }: { canManage?: boolean }) {
  return (
    <TableHeader className={TABLE_HEADER_CLASS}>
      <TableRow className="hover:bg-transparent">
        <TableHead className={TABLE_HEAD_CLASS}>Expense</TableHead>
        <TableHead className={TABLE_HEAD_CLASS}>Date</TableHead>
        <TableHead className={TABLE_HEAD_CLASS}>Payment method</TableHead>
        {canManage && <TableHead className={TABLE_HEAD_CLASS}>Created by</TableHead>}
        <TableHead className={cn(TABLE_HEAD_CLASS, "text-right")}>Amount</TableHead>
        {canManage && (
          <TableHead className={cn(TABLE_HEAD_CLASS, "w-0 text-right")}>
            <span className="sr-only">Actions</span>
          </TableHead>
        )}
      </TableRow>
    </TableHeader>
  )
}

function stopRowClick(event: MouseEvent) {
  event.stopPropagation()
}

/** Edit button + "more" menu — the same in a table row and a phone card. */
function RowActions({
  expense,
  onEdit,
  onDelete,
}: {
  expense: Expense
  onEdit: (expense: Expense) => void
  onDelete: (expense: Expense) => void
}) {
  const autoSource = expense.autoGeneratedSource
  return (
    <div className="flex justify-end gap-1">
      <Tooltip>
        <TooltipTrigger
          render={<Button variant="ghost" size="icon-sm" aria-label="Edit expense" onClick={() => onEdit(expense)} />}
        >
          <PencilIcon />
        </TooltipTrigger>
        <TooltipContent>Edit expense</TooltipContent>
      </Tooltip>
      <DropdownMenu>
        <DropdownMenuTrigger
          render={
            <Button
              variant="ghost"
              size="icon-sm"
              aria-label="More actions"
              className="data-popup-open:bg-accent data-popup-open:text-accent-foreground"
            />
          }
        >
          <MoreHorizontalIcon />
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-56">
          <DropdownMenuItem variant="destructive" disabled={!!autoSource} onClick={() => onDelete(expense)}>
            <Trash2Icon />
            <span className="leading-none">Delete expense</span>
          </DropdownMenuItem>
          {autoSource && (
            <p className="px-2 pt-1 pb-1.5 text-xs text-muted-foreground">
              {AUTO_SOURCE_LABELS[autoSource]}. {AUTO_DELETE_REASON}
            </p>
          )}
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  )
}

/** Neutral chip + dot (docs/design-system.md), with the generating release on hover. */
function AutoBadge({ source }: { source: ExpenseAutoSource }) {
  return (
    <Tooltip>
      <TooltipTrigger render={<span />} onClick={stopRowClick}>
        <Badge variant="secondary" className="gap-1.5">
          <span aria-hidden className="size-2 shrink-0 translate-y-px rounded-full bg-order-status-violet" />
          <span className="leading-none">Auto</span>
        </Badge>
      </TooltipTrigger>
      <TooltipContent>{AUTO_SOURCE_LABELS[source]}</TooltipContent>
    </Tooltip>
  )
}

export function ExpenseTable({
  footer,
  expenses,
  isLoading,
  isFetching,
  isError,
  error,
  hasActiveFilters,
  searchTerm,
  canManage,
  onClearFilters,
  onCreate,
  onEdit,
  onDelete,
}: {
  /** Rendered inside the table surface, below the rows (the pager). Hidden in loading/empty/error states. */
  footer?: ReactNode
  expenses: Expense[]
  isLoading?: boolean
  isFetching?: boolean
  isError?: boolean
  error?: string | null
  hasActiveFilters?: boolean
  searchTerm?: string
  canManage?: boolean
  onClearFilters?: () => void
  onCreate?: () => void
  onEdit: (expense: Expense) => void
  onDelete: (expense: Expense) => void
}) {
  if (isLoading) {
    return (
      <div className={TABLE_SURFACE_CLASS}>
        <DataCardListSkeleton />
        <Table className="max-md:hidden">
          <Columns canManage={canManage} />
          <TableBody>
            {Array.from({ length: 10 }).map((_, index) => (
              <TableRow key={index}>
                <TableCell className="px-4">
                  <div className="flex flex-col gap-1.5">
                    <Skeleton className="h-4 w-40" />
                    <Skeleton className="h-3 w-28" />
                  </div>
                </TableCell>
                <TableCell className="px-4">
                  <Skeleton className="h-4 w-24" />
                </TableCell>
                <TableCell className="px-4">
                  <Skeleton className="h-4 w-16" />
                </TableCell>
                {canManage && (
                  <TableCell className="px-4">
                    <Skeleton className="h-4 w-24" />
                  </TableCell>
                )}
                <TableCell className="px-4">
                  <Skeleton className="ml-auto h-4 w-20" />
                </TableCell>
                {canManage && (
                  <TableCell className="px-4">
                    <div className="flex justify-end gap-1">
                      <Skeleton className="size-7 rounded-md" />
                      <Skeleton className="size-7 rounded-md" />
                    </div>
                  </TableCell>
                )}
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    )
  }

  if (isError) {
    return (
      <Empty className={TABLE_SURFACE_CLASS}>
        <EmptyHeader>
          <EmptyMedia variant="icon">
            <TriangleAlertIcon />
          </EmptyMedia>
          <EmptyTitle>Couldn't load expenses</EmptyTitle>
          <EmptyDescription>{error ?? "Something went wrong."}</EmptyDescription>
        </EmptyHeader>
      </Empty>
    )
  }

  if (expenses.length === 0) {
    if (hasActiveFilters) {
      return (
        <Empty className={TABLE_SURFACE_CLASS}>
          <EmptyHeader>
            <EmptyMedia variant="icon">
              <ReceiptTextIcon />
            </EmptyMedia>
            <EmptyTitle>No expenses match your {searchTerm ? "search" : "filters"}</EmptyTitle>
            <EmptyDescription>
              {searchTerm
                ? `No results for "${searchTerm}". Try a different search or clear your filters.`
                : "Try adjusting or clearing your filters."}
            </EmptyDescription>
          </EmptyHeader>
          <EmptyContent>
            <Button variant="outline" size="sm" onClick={onClearFilters}>
              <XIcon data-icon="inline-start" />
              Clear filters
            </Button>
          </EmptyContent>
        </Empty>
      )
    }
    return (
      <Empty className={TABLE_SURFACE_CLASS}>
        <EmptyHeader>
          <EmptyMedia variant="icon">
            <ReceiptTextIcon />
          </EmptyMedia>
          <EmptyTitle>No expenses yet</EmptyTitle>
          <EmptyDescription>Get started by logging your first expense.</EmptyDescription>
        </EmptyHeader>
        <EmptyContent>
          <Button size="sm" onClick={onCreate}>
            <PlusIcon data-icon="inline-start" />
            Add expense
          </Button>
        </EmptyContent>
      </Empty>
    )
  }

  return (
    <div className="relative" aria-busy={isFetching}>
      <div className={cn(TABLE_SURFACE_CLASS, isFetching && "opacity-60 transition-opacity duration-150")}>
        <div className="hidden md:block">
          <Table>
            <Columns canManage={canManage} />
            <TableBody>
              {expenses.map((expense) => {
                const autoSource = expense.autoGeneratedSource
                return (
                  <TableRow
                    key={expense.id}
                    // Managers open the editor by clicking anywhere on the row (like Products/Orders).
                    onClick={
                      canManage
                        ? () => {
                            if (window.getSelection()?.toString()) return
                            onEdit(expense)
                          }
                        : undefined
                    }
                    className={cn(
                      canManage ? "cursor-pointer transition-colors duration-150 hover:bg-accent/40" : "hover:bg-transparent"
                    )}
                  >
                    <TableCell className="max-w-80 px-4">
                      <div className="flex min-w-0 flex-col gap-0.5">
                        <span className="flex min-w-0 items-center gap-2">
                          <span className="truncate font-medium">{expense.category}</span>
                          {autoSource && <AutoBadge source={autoSource} />}
                        </span>
                        <span className="truncate text-xs text-muted-foreground">
                          {expense.notes || "No notes"}
                        </span>
                      </div>
                    </TableCell>
                    <TableCell className="px-4 whitespace-nowrap">{formatDate(expense.date)}</TableCell>
                    <TableCell className="px-4 text-muted-foreground">{expense.paymentMethod}</TableCell>
                    {canManage && (
                      <TableCell className="px-4 whitespace-nowrap text-muted-foreground">
                        {expense.createdByName || "—"}
                      </TableCell>
                    )}
                    <TableCell className="px-4 text-right font-medium whitespace-nowrap tabular-nums">
                      {formatCurrency(expense.amount)}
                    </TableCell>
                    {canManage && (
                      <TableCell className="px-4" onClick={stopRowClick}>
                        <RowActions expense={expense} onEdit={onEdit} onDelete={onDelete} />
                      </TableCell>
                    )}
                  </TableRow>
                )
              })}
            </TableBody>
          </Table>
        </div>

        <DataCardList>
          {expenses.map((expense) => {
            const autoSource = expense.autoGeneratedSource
            return (
              <DataCardItem
                key={expense.id}
                aria-label={`${expense.category} expense`}
                onOpen={canManage ? () => onEdit(expense) : undefined}
              >
                <div className="flex items-start justify-between gap-3">
                  <div className="flex min-w-0 flex-col gap-0.5">
                    <span className="font-medium">{expense.category}</span>
                    <span className="text-xs text-muted-foreground">
                      {formatDate(expense.date)} · {expense.paymentMethod}
                    </span>
                  </div>
                  <span className="shrink-0 font-medium tabular-nums">{formatCurrency(expense.amount)}</span>
                </div>
                {expense.notes ? <p className="line-clamp-2 text-muted-foreground">{expense.notes}</p> : null}
                {(autoSource || canManage) && (
                  <div className="flex items-center justify-between gap-3">
                    <div className="flex min-w-0 flex-col gap-1 text-xs text-muted-foreground">
                      {/* Spelled out here: the table's hover tooltip isn't reachable on touch. */}
                      {autoSource ? <span>{AUTO_SOURCE_LABELS[autoSource]}</span> : null}
                      {canManage && expense.createdByName ? <span>Added by {expense.createdByName}</span> : null}
                    </div>
                    {canManage && (
                      <div className="-mr-2 shrink-0" onClick={stopRowClick}>
                        <RowActions expense={expense} onEdit={onEdit} onDelete={onDelete} />
                      </div>
                    )}
                  </div>
                )}
              </DataCardItem>
            )
          })}
        </DataCardList>
        {footer}
      </div>
      {isFetching && (
        <div className="absolute top-3 right-3 flex items-center gap-1.5 rounded-full bg-background/90 px-2 py-1 text-xs text-muted-foreground shadow-sm ring-1 ring-border">
          <Loader2Icon className="size-3.5 animate-spin" />
          Updating…
        </div>
      )}
    </div>
  )
}
