import { LockIcon, ReceiptTextIcon } from "lucide-react"
import { useEffect, useState } from "react"
import { format, parseISO } from "date-fns"
import { toast } from "sonner"

import { CharCount } from "@/components/char-count"
import { ChoiceTile } from "@/components/choice-tile"
import { Button } from "@/components/ui/button"
import { Calendar } from "@/components/ui/calendar"
import { FormDialogHeader } from "@/components/form-dialog-header"
import { Dialog, DialogBody, DialogContent, DialogFooter } from "@/components/ui/dialog"
import { CurrencyInput } from "@/components/ui/currency-input"
import { Field, FieldError, FieldGroup, FieldLabel } from "@/components/ui/field"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Spinner } from "@/components/ui/spinner"
import { Textarea } from "@/components/ui/textarea"
import { ToggleGroup } from "@/components/ui/toggle-group"
import {
  EXPENSE_CATEGORIES,
  useExpenseActions,
  type Expense,
  type ExpenseAutoSource,
  type ExpenseInput,
} from "@/lib/expenses"
import { useEnabledPaymentMethods } from "@/lib/payment-methods"
import { cn } from "@/lib/utils"
import { maxLengthMessage, parsePositiveAmount, positiveAmountMessage, requiredMessage } from "@/lib/validation"

const NOTES_MAX_LENGTH = 300

const AUTO_SOURCE_TITLES: Record<ExpenseAutoSource, string> = {
  commission_release: "Created by a commission release",
  monthly_incentive_release: "Created by a monthly incentive release",
}

function emptyDraft(): ExpenseInput {
  return {
    date: format(new Date(), "yyyy-MM-dd"),
    amount: 0,
    category: "",
    paymentMethod: "",
    notes: "",
  }
}

function draftFromExpense(expense: Expense): ExpenseInput {
  return {
    date: expense.date,
    amount: expense.amount,
    category: expense.category,
    paymentMethod: expense.paymentMethod,
    notes: expense.notes,
  }
}

export function ExpenseFormDialog({
  open,
  onOpenChange,
  expense,
  onSaved,
}: {
  open: boolean
  onOpenChange: (open: boolean) => void
  expense: Expense | null
  onSaved?: () => void
}) {
  const { addExpense, updateExpense } = useExpenseActions()
  const { paymentMethods: enabledMethods } = useEnabledPaymentMethods()
  const autoSource = expense?.autoGeneratedSource ?? null
  const isLocked = !!autoSource
  const [draft, setDraft] = useState<ExpenseInput>(emptyDraft)
  const [amountInput, setAmountInput] = useState("")
  const [dateError, setDateError] = useState<string | null>(null)
  const [amountError, setAmountError] = useState<string | null>(null)
  const [categoryError, setCategoryError] = useState<string | null>(null)
  const [paymentMethodError, setPaymentMethodError] = useState<string | null>(null)
  const [notesError, setNotesError] = useState<string | null>(null)
  const [isSubmitting, setIsSubmitting] = useState(false)

  useEffect(() => {
    if (!open) return
    const next = expense ? draftFromExpense(expense) : emptyDraft()
    setDraft(next)
    setAmountInput(expense ? String(expense.amount) : "")
    setDateError(null)
    setAmountError(null)
    setCategoryError(null)
    setPaymentMethodError(null)
    setNotesError(null)
  }, [open, expense])

  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault()

    if (!draft.date) {
      setDateError(requiredMessage("Date"))
      return
    }
    const amount = parsePositiveAmount(amountInput)
    if (amount === null) {
      setAmountError(positiveAmountMessage("amount"))
      return
    }
    if (!draft.category) {
      setCategoryError(requiredMessage("Category"))
      return
    }
    if (!draft.paymentMethod) {
      setPaymentMethodError(requiredMessage("Payment method"))
      return
    }
    if (draft.notes.length > NOTES_MAX_LENGTH) {
      setNotesError(maxLengthMessage("Notes", NOTES_MAX_LENGTH))
      return
    }

    const payload: ExpenseInput = { ...draft, amount }

    setIsSubmitting(true)
    try {
      if (expense) {
        await updateExpense(expense.id, payload)
        toast.success("Expense updated.")
      } else {
        await addExpense(payload)
        toast.success("Expense created.")
      }
      onOpenChange(false)
      onSaved?.()
    } catch (err) {
      toast.error(typeof err === "string" ? err : "Failed to save expense.")
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <FormDialogHeader
          icon={ReceiptTextIcon}
          title={<>{expense ? "Edit expense" : "New expense"}</>}
          description={<>{expense ? "Update this expense's details." : "Log a new business expense."}</>}
        />

        <DialogBody>
        <form id="expense-form" onSubmit={handleSubmit} className="flex flex-col gap-4">
          {autoSource && (
            <div className="flex gap-2.5 rounded-lg border bg-muted/40 px-3 py-2.5 text-sm">
              <LockIcon aria-hidden className="mt-0.5 size-4 shrink-0 text-muted-foreground" />
              <div className="flex flex-col gap-0.5">
                <span className="font-medium">{AUTO_SOURCE_TITLES[autoSource]}</span>
                <span className="text-muted-foreground">
                  Amount, category and date are locked. Undo the release on the Incentives page to change them.
                </span>
              </div>
            </div>
          )}
          <FieldGroup>
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <Field data-invalid={!!amountError}>
                <FieldLabel htmlFor="expense-amount">Amount</FieldLabel>
                <CurrencyInput
                  id="expense-amount"
                  value={amountInput}
                  disabled={isLocked}
                  onChange={(event) => {
                    setAmountInput(event.target.value)
                    setAmountError(null)
                  }}
                  aria-invalid={!!amountError}
                />
                <FieldError>{amountError ?? undefined}</FieldError>
              </Field>

              <Field data-invalid={!!dateError}>
                <FieldLabel htmlFor="expense-date">Date</FieldLabel>
                <Popover>
                  <PopoverTrigger
                    id="expense-date"
                    disabled={isLocked}
                    render={
                      <Button
                        type="button"
                        variant="outline"
                        className="w-full justify-start font-normal"
                        aria-invalid={!!dateError}
                      />
                    }
                  >
                    {draft.date ? format(parseISO(draft.date), "MMM d, yyyy") : "Select date"}
                  </PopoverTrigger>
                  <PopoverContent className="w-auto p-0" align="start">
                    <Calendar
                      mode="single"
                      selected={draft.date ? parseISO(draft.date) : undefined}
                      onSelect={(date) => {
                        setDraft((prev) => ({ ...prev, date: date ? format(date, "yyyy-MM-dd") : "" }))
                        setDateError(null)
                      }}
                      autoFocus
                    />
                  </PopoverContent>
                </Popover>
                <FieldError>{dateError ?? undefined}</FieldError>
              </Field>
            </div>

            <Field data-invalid={!!categoryError}>
              <FieldLabel htmlFor="expense-category">Category</FieldLabel>
              <Select
                value={draft.category || undefined}
                disabled={isLocked}
                onValueChange={(value) => {
                  setDraft((prev) => ({ ...prev, category: value ?? "" }))
                  setCategoryError(null)
                }}
              >
                <SelectTrigger id="expense-category" className="w-full" aria-invalid={!!categoryError}>
                  <SelectValue placeholder="Select a category" />
                </SelectTrigger>
                <SelectContent className="min-w-64">
                  {EXPENSE_CATEGORIES.map((category) => (
                    <SelectItem key={category} value={category}>
                      {category}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <FieldError>{categoryError}</FieldError>
            </Field>

            <Field data-invalid={!!paymentMethodError}>
              <FieldLabel htmlFor="expense-payment-method">Payment method</FieldLabel>
              <ToggleGroup
                id="expense-payment-method"
                value={draft.paymentMethod ? [draft.paymentMethod] : []}
                onValueChange={(next) => {
                  const value = next[0]
                  if (value) {
                    setDraft((prev) => ({ ...prev, paymentMethod: value }))
                    setPaymentMethodError(null)
                  }
                }}
                className={cn(
                  "flex-wrap gap-2",
                  paymentMethodError && "rounded-lg ring-1 ring-destructive ring-offset-2 ring-offset-background"
                )}
              >
                {/* Merge in the current value even if it's since been disabled/deleted in
                  Settings, so an existing expense using a retired method still renders. */}
                {(draft.paymentMethod && !enabledMethods.includes(draft.paymentMethod)
                  ? [...enabledMethods, draft.paymentMethod]
                  : enabledMethods
                ).map((method) => (
                  <ChoiceTile key={method} value={method}>
                    {method}
                  </ChoiceTile>
                ))}
              </ToggleGroup>
              <FieldError>{paymentMethodError}</FieldError>
            </Field>

            <Field data-invalid={!!notesError}>
              <div className="flex items-baseline justify-between gap-2">
                <FieldLabel htmlFor="expense-notes">
                  Notes <span className="font-normal text-muted-foreground">(optional)</span>
                </FieldLabel>
                <CharCount value={draft.notes} max={NOTES_MAX_LENGTH} />
              </div>
              <Textarea
                id="expense-notes"
                value={draft.notes}
                onChange={(event) => {
                  setDraft((prev) => ({ ...prev, notes: event.target.value }))
                  setNotesError(null)
                }}
                placeholder="Vendor, reason, or other context"
                maxLength={NOTES_MAX_LENGTH}
                aria-invalid={!!notesError}
              />
              <FieldError>{notesError ?? undefined}</FieldError>
            </Field>
          </FieldGroup>
        </form>
        </DialogBody>

        <DialogFooter>
          <Button variant="ghost" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button type="submit" form="expense-form" disabled={isSubmitting}>
            {isSubmitting && <Spinner data-icon="inline-start" />}
            {isSubmitting ? "Saving…" : expense ? "Save changes" : "Add expense"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
